FS-11659 [core] Fix implicit declaration of RAND_bytes
Since the update to openssl-1.1.1a the compile fails like this:

  CC       src/libfreeswitch_la-switch_rtp.lo
src/switch_rtp.c: In function 'switch_rtp_get_random':
src/switch_rtp.c:2419:2: error: implicit declaration of function 'RAND_bytes'; did you mean 'RSA_bits'? [-Werror=implicit-function-declaration]
  RAND_bytes(buf, len);
  ^~~~~~~~~~
  RSA_bits
cc1: all warnings being treated as errors
make[4]: *** [Makefile:2377: src/libfreeswitch_la-switch_rtp.lo] Error 1

This patch adds the missing include.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>